
[general]
	#An example enum DyeColor in the client config
	clientEnumDyeColor = "WHITE"
	#If the model should be rendered translucent
	modelTranslucency = true
	#An example boolean in the client config
	clientBoolean = true
	#The scale to render the model at
	#Range: 1.0E-4 ~ 100.0
	modelScale = 0.0625
	#An example list of Strings in the client config
	clientStringList = []

